name: VPS Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show LocalXpose Version
        run: |
          wget https://api.localxpose.io/api/v2/downloads/loclx-linux-amd64.deb
          sudo dpkg -i loclx-linux-amd64.deb

          loclx version

      - name: Show Help
        run: |
          loclx account --help || true
          loclx account login --help || true
