name: LocalXpose Test

on:
workflow_dispatch:

jobs:
test:
runs-on: ubuntu-latest

steps:
  - name: Install LocalXpose
    run: |
      wget https://api.localxpose.io/api/v2/downloads/loclx-linux-amd64.deb
      sudo dpkg -i loclx-linux-amd64.deb

  - name: Check Version
    run: |
      loclx --version

  - name: Show Login Help
    run: |
      loclx account login --help

  - name: Show Account Help
    run: |
      loclx account --help
